app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_sonata_admin:
    resource: "@"
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }