app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }
