# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt
            AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_AUTHOR:      ROLE_AUTHOR
        ROLE_MODERATOR:   ROLE_MODERATOR
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false

        default:
          anonymous: ~
#    firewalls:
#        main:
#            pattern: ^/
#            form_login:
#              login_path: login
#              check_path: login
#
#            logout:       true
#            anonymous:    true
#
#    access_control:
#      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#      - { path: ^/, roles: ROLE_ADMIN }