# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt
            AppBundle\Entity\User: bcrypt
            Symfony\Component\Security\Core\User\User:
              algorithm: plaintext

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_MODERATOR:   ROLE_MODERATOR

    providers:
      in_memory:
        memory:
          users:
            admin:
              password: admin
              roles: 'ROLE_ADMIN'

      fos_userbundle:
          id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
              login_path: login
              check_path: login

            logout:       true
            anonymous:    true

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin, roles: ROLE_ADMIN }

